import 'package:firebase_auth/firebase_auth.dart';
import 'package:laboratory5/backend/services/database_service.dart';

class AuthService {
  final FirebaseAuth _auth = FirebaseAuth.instance;

  /*
  Q1: Firebase Authentication Flow in this Code

  1. USER REGISTRATION STARTS (App triggers signUp)
     → This function is called when a user submits email & password.
  */

  // Sign up
  Future<UserCredential?> signUp(String email, String password) async {
    try {
      /*
      2. FIREBASE AUTH CREATES USER ACCOUNT
         → Firebase sends credentials to its servers
         → Creates a new authenticated user
         → Returns a UserCredential object
      */
      UserCredential userCredential = await FirebaseAuth.instance
          .createUserWithEmailAndPassword(email: email, password: password);

      /*
      3. FIREBASE RETURNS UNIQUE USER ID (UID)
         → userCredential.user!.uid is generated by Firebase
         → This UID is used as the user's identity across the app
      */

      /*
      4. FIRESTORE PROFILE CREATION
         → After authentication, we store additional user info in Firestore
         → This links Firebase Auth user to database profile
      */
      await DatabaseService().createUserProfile(
        userCredential.user!.uid,
        email,
      );

      /*
      5. RETURN SUCCESSFUL LOGIN RESULT
         → The app now knows the user is authenticated
      */
      return userCredential;
    } catch (e) {
      /*
      6. ERROR HANDLING
         → If authentication fails (wrong email/password, etc.)
      */
      print("Sign up error: $e");
      return null;
    }
  }

  /*
  7. LOGIN FLOW
     → User enters credentials again
     → Firebase verifies credentials against stored account
  */
  Future<UserCredential?> signIn(String email, String password) async {
    try {
      return await _auth.signInWithEmailAndPassword(
        email: email,
        password: password,
      );
    } catch (e) {
      print(e.toString());
      return null;
    }
  }

  /*
  8. LOGOUT FLOW
     → Firebase removes the current session
     → User becomes unauthenticated
     → AuthGate will redirect them back to login screen
  */
  Future<void> signOut() async {
    await _auth.signOut();
  }
}
